package main;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

// Start of user code for imports
// End of user code

/**
 * ActionCard class definition.
 * Generated by the TouchCORE code generator.
 */
public class ActionCard extends Card implements SerializableSFSType {
    
    protected ActionKind action;
    protected boolean saveForNextRound;
    
}
