package main;


import java.util.ArrayList;

// Start of user code for imports
// End of user code

/**
 * ActionCard class definition.
 * Generated by the TouchCORE code generator.
 */
class ActionCard {
    
    protected ActionKind action;
    protected boolean saveForNextRound;
    protected boolean bullet;
    protected Bandit belongsTo;
    
    Bandit getBelongsTo() {
        return this.belongsTo;
    }

    boolean setBelongsTo(Bandit newObject) {
        this.belongsTo = newObject;
        return true;
    }
}
