package main;

import java.util.ArrayList;

// Start of user code for imports
// End of user code

/**
 * Horse class definition.
 * Generated by the TouchCORE code generator.
 */
class Horse {
    
}
