package main;

import java.util.ArrayList;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

// Start of user code for imports
// End of user code

/**
 * Horse class definition.
 * Generated by the TouchCORE code generator.
 */
public class Horse implements SerializableSFSType {
    
}
