package main;

// Start of user code for imports
// End of user code

/**
 * Hostage class definition.
 * Generated by the TouchCORE code generator.
 */
class Hostage {
    
    protected HostageType hostageType;
    protected Bandit capturedBy;
    
    Bandit getCapturedBy() {
        return this.capturedBy;
    }

    boolean setCapturedBy(Bandit newObject) {
        this.capturedBy = newObject;
        return true;
    }
}
