package main;

// Start of user code for imports
// End of user code

/**
 * Marshal class definition.
 * Generated by the TouchCORE code generator.
 */
class Marshal {
    
    protected TrainUnit marshalPosition;
    protected static Marshal instance;
    
    TrainUnit getMarshalPosition() {
        return this.marshalPosition;
    }

    boolean setMarshalPosition(TrainUnit newObject) {
        this.marshalPosition = newObject;
        return true;
    }

    public Marshal() {
        /* TODO: No message view defined */
    }
}
