package main;

// Start of user code for imports
// End of user code

/**
 * Money class definition.
 * Generated by the TouchCORE code generator.
 */
class Money extends Loot {
    
    protected int value;
    protected MoneyType moneyType;
    
}
