package main;

import java.util.ArrayList;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

// Start of user code for imports
// End of user code

/**
 * Turn class definition.
 * Generated by the TouchCORE code generator.
 */
public class Turn implements SerializableSFSType {
    
    protected TurnType turn;
    
}
