package main;

import java.util.ArrayList;

// Start of user code for imports
// End of user code

/**
 * Turn class definition.
 * Generated by the TouchCORE code generator.
 */
class Turn {
    
    protected TurnType turn;
    
}
