package main;

// Start of user code for imports
// End of user code

/**
 * Whiskey class definition.
 * Generated by the TouchCORE code generator.
 */
class Whiskey extends Loot {
    
    protected WhiskeyType whiskeyType;
    protected WhiskeyStatus whiskeyStatus;
    
}
