package model;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

// Start of user code for imports
// End of user code

/**
 * ActionCard class definition.
 * Generated by the TouchCORE code generator.
 */
public class ActionCard extends Card implements SerializableSFSType {
    
    protected ActionKind action;
    protected boolean saveForNextRound = false;
    protected boolean faceDown = false;
    
    public ActionCard(ActionKind ak) {
		this.action = ak;
	}
    
    public void setAction(ActionKind a) {
        this.action = a;
    }

    public void setSaveForNextRound(boolean b) {
        this.saveForNextRound = b;
    }

    public boolean getSaveForNextRound(){
        return this.saveForNextRound;
    }

    public ActionKind getAction() {
        return this.action;
    }

    public boolean getFaceDown() { return this.faceDown; }

    public void setFaceDown(boolean b) { this.faceDown = b; }
}
