package model;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

/**
 * ActionKind enumeration definition.
 * Generated by the TouchCORE code generator.
 */
public enum ActionType implements SerializableSFSType {
	MOVE, CHANGEFLOOR, SHOOT, ROB, MARSHAL, PUNCH
}
