package model;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

// Start of user code for imports
// End of user code

/**
 * ActionCard class definition.
 * Generated by the TouchCORE code generator.
 */
public class ActionCard extends Card implements SerializableSFSType {
    
    transient public ActionType actionType;
    public String actionTypeAsString; //FOR NETWORKING
    public boolean saveForNextRound = false;
    public boolean faceDown = false;
    public String belongsToAsString;
    
    //--EMPTY CONSTRUCTOR FOR SERIALIZATION--
    public ActionCard() {}
    
    public ActionCard(ActionType action, String belongsTo) {
		this.actionType = action;
		this.actionTypeAsString = action.name();
		super.belongsToAsString = belongsTo;
	}    
    
    /**
     * --GETTERS AND SETTERS--
     */

    //actionType
    public ActionType getActionType() {
        return this.actionType;
    }    
    public void setActionType(ActionType action) {
        this.actionType = action;
    }

    //actionTypeAsString
    public String getActionTypeAsString() {
    	return this.actionTypeAsString;
    }
    public void setActionTypeAsString(String action) {
    	this.actionTypeAsString = action;
    }
    
    //saveForNextRound
     public boolean getSaveForNextRound(){
        return this.saveForNextRound;
    }   
    public void setSaveForNextRound(boolean b) {
        this.saveForNextRound = b;
    }

    //faceDown
    public boolean getFaceDown() {
    	return this.faceDown;
    }
    public void setFaceDown(boolean b) { 
    	this.faceDown = b;
    }
    
    public String getBelongsTo() {
        return this.belongsToAsString;
    }

    public void setBelongsTo(String belongsTo) {
        this.belongsToAsString = belongsTo;
    }
}
