package model;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

/**
 * CarType enumeration definition. Generated by the TouchCORE code generator.
 */
public enum CarType implements SerializableSFSType {
	LOCOMOTIVE, CAR1, CAR2, CAR3, CAR4, CAR5, CAR6
}
