package model;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

/**
 * Character enumeration definition.
 * Generated by the TouchCORE code generator.
 */
public enum Character implements SerializableSFSType {
    GHOST, DOC, TUCO, CHEYENNE, BELLE, DJANGO
}
