package model;

import java.util.Optional;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

// Start of user code for imports
// End of user code

/**
 * Horse class definition.
 * Generated by the TouchCORE code generator.
 */
public class Horse implements SerializableSFSType {
	
	public TrainUnit adjacentTo;
	public Optional<Bandit> riddenBy;
	
	//--EMPTY CONSTRUCTOR FOR SERIALIZATION--
    public Horse() { }
    
    
    /**
     * --GETTERS AND SETTERS--
     */
    
    //adjacentTo
    public TrainUnit getAdjacentTo() {
    	return this.adjacentTo;
    }
    public void setAdjacentTo(TrainUnit adjacentTo) {
    	this.adjacentTo = adjacentTo;
    }
    
    //riddenBy
    public Bandit getRiddenBy() {
    	return this.riddenBy.get();
    }
    public void setRiddenBy(Bandit b) {
    	this.riddenBy = Optional.ofNullable(b);
    }
}
