package model;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

// Start of user code for imports
// End of user code

/**
 * Hostage class definition.
 * Generated by the TouchCORE code generator.
 */
public class Hostage implements SerializableSFSType {
    
    protected HostageType hostageType;
    protected Bandit capturedBy;
    
  //--EMPTY CONSTRUCTOR FOR SERIALIZATION--
    public Hostage() { }
    
    public Bandit getCapturedBy() {
        return this.capturedBy;
    }

    public void setCapturedBy(Bandit newObject) {
        this.capturedBy = newObject;
    }

    public HostageType getHostageType(){
        return this.hostageType;
    }

    public void setHostageType(HostageType p) {
        this.hostageType=p;
    }
}
