package model;

import java.util.Optional;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

// Start of user code for imports
// End of user code

/**
 * Loot class definition.
 * Generated by the TouchCORE code generator.
 */
public abstract class Loot implements SerializableSFSType {
    
	public Optional<Bandit> belongsTo;
	public Optional<TrainUnit> position;
    
    //--EMPTY CONSTRUCTOR FOR SERIALIZATION--
    public Loot() { }
    
    /**
     * --LOOT METHODS--
     */
    public void drop() {
    	//TODO
    }
    public void pickup() {
    	//TODO
    }
    
}
