package model;

import java.util.ArrayList;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

// Start of user code for imports
// End of user code

/**
 * Loot class definition.
 * Generated by the TouchCORE code generator.
 */
public abstract class Loot implements SerializableSFSType {
    
    protected boolean isWhiskey;
    
    //--EMPTY CONSTRUCTOR FOR SERIALIZATION--
    public Loot() { }

    public void setIsWhiskey(boolean b){
        this.isWhiskey=b;
    }

    public boolean getIsWhiskey(){
        return this.isWhiskey;
    }
}
