package model;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

// Start of user code for imports
// End of user code

/**
 * Marshal class definition.
 * Generated by the TouchCORE code generator.
 */
public class Marshal implements SerializableSFSType {
    
    public TrainUnit marshalPosition;
    public static Marshal instance;

  //--EMPTY CONSTRUCTOR FOR SERIALIZATION--
    //public Marshal() {}
    
    public static Marshal createMarshal() {
    	getInstance();
    	final int x = TrainUnit.getTrainLength();
    	TrainUnit t = TrainUnit.getTrain()[1][x-1];
    	instance.marshalPosition = t;
    	return instance;
    }
    
    public TrainUnit getMarshalPosition() {
        return this.marshalPosition;
    }

    public void setMarshalPosition(TrainUnit pos) {
        this.marshalPosition = pos;
    }

    public static Marshal getInstance(){
        if (instance==null){
            instance = new Marshal();
        }
        return instance;
    }
}
