package model;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

// Start of user code for imports
// End of user code

/**
 * Marshal class definition.
 * Generated by the TouchCORE code generator.
 */
public class Marshal implements SerializableSFSType {
    
    public TrainUnit marshalPosition;
    public static Marshal instance;

  //--EMPTY CONSTRUCTOR FOR SERIALIZATION--
    public Marshal() {}
    
    public static Marshal create() {
    	//TODO
    }
    
    public TrainUnit getMarshalPosition() {
        return this.marshalPosition;
    }

    public void setMarshalPosition(TrainUnit pos) {
        this.marshalPosition = pos;
    }

    public static Marshal getInstance(){
        if (instance==null){
            instance = new Marshal();
        }
        return instance;
    }
}
