package model;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

// Start of user code for imports
// End of user code

/**
 * Money class definition.
 * Generated by the TouchCORE code generator.
 */
public class Money extends Loot implements SerializableSFSType {
    
    protected int value;
    protected MoneyType moneyType;
    
    public Money() { }
    
	public Money(MoneyType mt, int value) {
		this.moneyType = mt;
		this.value = value;
	}
    
    public void setValue(int v){
        this.value=v;
    }

    public int getValue(){
        return this.value;
    }

    public void setMoneyType(MoneyType p){
        this.moneyType = p;
    }

    public MoneyType getMoneyType(){
        return this.moneyType;
    }
    
}
