package model;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

/**
 * RoundType enumeration definition.
 * Generated by the TouchCORE code generator.
 */
public enum RoundType implements SerializableSFSType {
    AngryMarshal, SwivelArm, Braking, TakeItAll, PassengersRebellion, Bridge, Cave
}
