package model;

import java.util.ArrayList;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

// Start of user code for imports
// End of user code

/**
 * Turn class definition.
 * Generated by the TouchCORE code generator.
 */
public class Turn implements SerializableSFSType {
    
    transient public TurnType turnType;
	public String turnTypeAsString; // FOR NETWORKING
    
    //--EMPTY CONSTRUCTOR FOR SERIALIZATION--
    public Turn() { }

    
    /**
     * --GETTERS AND SETTERS--
     */
    
    //turnType
    public TurnType getTurnType(){
        return this.turnType;
    }
    
    public void setTurnType(TurnType p){
        this.turnType = p;
    }
    
    //turnTypeAsString
    public String getTurnTypeAsString() {
    	return this.turnTypeAsString;
    }
    public void setTurnTypeAsString(String s) {
    	this.turnTypeAsString = s;
    }
}
