package model;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

/**
 * TurnType enumeration definition.
 * Generated by the TouchCORE code generator.
 */
public enum TurnType implements SerializableSFSType {

}
