package model;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

/**
 * WhiskeyStatus enumeration definition.
 * Generated by the TouchCORE code generator.
 */
public enum WhiskeyStatus implements SerializableSFSType {

}
