package model;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

// Start of user code for imports
// End of user code

/**
 * Whiskey class definition.
 * Generated by the TouchCORE code generator.
 */
public class Whiskey extends Loot implements SerializableSFSType {
    
    protected WhiskeyType whiskeyType;
    protected WhiskeyStatus whiskeyStatus;
    

    //--EMPTY CONSTRUCTOR FOR SERIALIZATION--
    public Whiskey() { }

    public WhiskeyType getWhiskeyType(){
        return this.whiskeyType;
    }

    public WhiskeyStatus getWhiskeyStatus(){
        return this.whiskeyStatus;
    }

    public void setWhiskeyType(WhiskeyType p){
        this.whiskeyType = p;
    }

    public void setWhiskeyStatus(WhiskeyStatus p){
        this.whiskeyStatus = p;
    }
}
