package model;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

/**
 * CarType enumeration definition. Generated by the TouchCORE code generator.
 */
public enum CarFloor implements SerializableSFSType {
	CABIN, ROOF
}