package model;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

// Start of user code for imports
// End of user code

/**
 * Whiskey class definition.
 * Generated by the TouchCORE code generator.
 */
public class Whiskey extends Loot implements SerializableSFSType {
    
    transient public WhiskeyType whiskeyType;
    public String whiskeyTypeAsString; //FOR NETWORKING
    transient public WhiskeyStatus whiskeyStatus;
    public String whiskeyStatusAsString; //FOR NETWORKING
    

    //--EMPTY CONSTRUCTOR FOR SERIALIZATION--
    public Whiskey() { }

    public Whiskey(WhiskeyType w) {
    	this.whiskeyType = w;
    	this.whiskeyTypeAsString = w.name();
    	this.whiskeyStatus = WhiskeyStatus.UNFLIPPED;
    	this.whiskeyStatusAsString = whiskeyStatus.name();
    }
    /**
     * --GETTERS AND SETTERS--
     */
    
    //whiskeyType
    public WhiskeyType getWhiskeyType(){
        return this.whiskeyType;
    }
    public void setWhiskeyType(WhiskeyType p){
        this.whiskeyType = p;
    }
    
    //whiskeyTypeAsString
    public String getWhiskeyTypeAsString() {
    	return this.whiskeyTypeAsString;
    }
    public void setWhiskeyTypeAsString(String s) {
    	this.whiskeyTypeAsString = s;
    }
    
    //whiskeyStatus
    public WhiskeyStatus getWhiskeyStatus(){
        return this.whiskeyStatus;
    }
    public void setWhiskeyStatus(WhiskeyStatus p){
        this.whiskeyStatus = p;
    }
    
    //whiskeyStatusAsString
    public String getWhiskeyStatusAsString() {
    	return this.whiskeyStatusAsString;
    }
    public void setWhiskeyStatusAsString(String s) {
    	this.whiskeyStatusAsString = s;
    }
}
