package model;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

/**
 * WhiskeyType enumeration definition.
 * Generated by the TouchCORE code generator.
 */
public enum WhiskeyType implements SerializableSFSType {
	NORMAL, OLD
}
