package main;

import java.util.ArrayList;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

// Start of user code for imports
// End of user code

/**
 * Bandit class definition. Generated by the TouchCORE code generator.
 */
public class Bandit implements SerializableSFSType {

	protected boolean getsAnotherAction;
	protected boolean playedThisTurn;
	protected Character banditName;
	protected TrainUnit position;
	protected Hostage hostage;
	protected ArrayList<Loot> loot = new ArrayList<Loot>();
	protected ArrayList<BulletCard> bullets = new ArrayList<BulletCard>();;
	protected ArrayList<ActionCard> deck = new ArrayList<ActionCard>();;
	protected ArrayList<ActionCard> hand = new ArrayList<ActionCard>();;
	protected ArrayList<ActionCard> discardPile = new ArrayList<ActionCard>();;

	public Bandit(Character c) {
		this.banditName = c;
		this.getsAnotherAction = false;
		this.playedThisTurn = false;
		this.position = null;
		this.hostage = null;
	}

	public void setGetsAnotherAction(boolean anotherAction) {
		this.getsAnotherAction = anotherAction;
	}

	public boolean getGetsAnotherAction() {
		return this.getsAnotherAction;
	}

	public boolean getPlayedThisTurn() {
		return this.playedThisTurn;
	}

	public void setPlayedThisTurn(boolean played) {
		this.playedThisTurn = played;
	}

	TrainUnit getPosition() {
		return this.position;
	}

	boolean setPosition(TrainUnit newObject) {
		this.position = newObject;
		return true;
	}

	boolean addLootAt(int index, Loot a) {
		boolean contains = loot.contains(a);
		if (contains) {
			return false;
		}
		loot.add(index, a);
		return true;
	}

	boolean removeLootAt(int index) {
		Loot removedElement = loot.remove(index);
		boolean result = removedElement != null;
		return result;
	}

	Loot getLootAt(int index) {
		Loot associated = loot.get(index);
		return associated;
	}

	boolean addLoot(Loot a) {
		boolean contains = loot.contains(a);
		if (contains) {
			return false;
		}
		boolean added = loot.add(a);
		return added;
	}

	boolean removeLoot(Loot a) {
		boolean removed = loot.remove(a);
		return removed;
	}

	boolean containsLoot(Loot a) {
		boolean contains = loot.contains(a);
		return contains;
	}

	int sizeOfLoot() {
		int size = loot.size();
		return size;
	}

	ArrayList<Loot> getLoot() {
		return this.loot;
	}

	boolean addDeckAt(int index, ActionCard a) {
		boolean contains = deck.contains(a);
		if (contains) {
			return false;
		}
		deck.add(index, a);
		return true;
	}

	boolean removeDeckAt(int index) {
		ActionCard removedElement = deck.remove(index);
		boolean result = removedElement != null;
		return result;
	}

	ActionCard getDeckAt(int index) {
		ActionCard associated = deck.get(index);
		return associated;
	}

	boolean addDeck(ActionCard a) {
		boolean contains = deck.contains(a);
		if (contains) {
			return false;
		}
		boolean added = deck.add(a);
		return added;
	}

	boolean removeDeck(ActionCard a) {
		boolean removed = deck.remove(a);
		return removed;
	}

	boolean containsDeck(ActionCard a) {
		boolean contains = deck.contains(a);
		return contains;
	}

	int sizeOfDeck() {
		int size = deck.size();
		return size;
	}

	ArrayList<ActionCard> getDeck() {
		return this.deck;
	}

	boolean addHandAt(int index, ActionCard a) {
		boolean contains = hand.contains(a);
		if (contains) {
			return false;
		}
		hand.add(index, a);
		return true;
	}

	boolean removeHandAt(int index) {
		ActionCard removedElement = hand.remove(index);
		boolean result = removedElement != null;
		return result;
	}

	ActionCard getHandAt(int index) {
		ActionCard associated = hand.get(index);
		return associated;
	}

	boolean addHand(ActionCard a) {
		boolean contains = hand.contains(a);
		if (contains) {
			return false;
		}
		boolean added = hand.add(a);
		return added;
	}

	boolean removeHand(ActionCard a) {
		boolean removed = hand.remove(a);
		return removed;
	}

	boolean containsHand(ActionCard a) {
		boolean contains = hand.contains(a);
		return contains;
	}

	int sizeOfHand() {
		int size = hand.size();
		return size;
	}

	ArrayList<ActionCard> getHand() {
		return this.hand;
	}

	boolean addDiscardPileAt(int index, ActionCard a) {
		boolean contains = discardPile.contains(a);
		if (contains) {
			return false;
		}
		discardPile.add(index, a);
		return true;
	}

	boolean removeDiscardPileAt(int index) {
		ActionCard removedElement = discardPile.remove(index);
		boolean result = removedElement != null;
		return result;
	}

	ActionCard getDiscardPileAt(int index) {
		ActionCard associated = discardPile.get(index);
		return associated;
	}

	boolean addDiscardPile(ActionCard a) {
		boolean contains = discardPile.contains(a);
		if (contains) {
			return false;
		}
		boolean added = discardPile.add(a);
		return added;
	}

	boolean removeDiscardPile(ActionCard a) {
		boolean removed = discardPile.remove(a);
		return removed;
	}

	boolean containsDiscardPile(ActionCard a) {
		boolean contains = discardPile.contains(a);
		return contains;
	}

	int sizeOfDiscardPile() {
		int size = discardPile.size();
		return size;
	}

	ArrayList<ActionCard> getDiscardPile() {
		return this.discardPile;
	}

	Hostage getHostage() {
		return this.hostage;
	}

	boolean setHostage(Hostage newObject) {
		this.hostage = newObject;
		return true;
	}

	void createStartingCards() {

		ActionCard acMove1 = new ActionCard(ActionKind.MOVE);
		ActionCard acMove2 = new ActionCard(ActionKind.MOVE);
		ActionCard acChangeFloor1 = new ActionCard(ActionKind.CHANGEFLOOR);
		ActionCard acChangeFloor2 = new ActionCard(ActionKind.CHANGEFLOOR);
		ActionCard acMarshal = new ActionCard(ActionKind.MARSHAL);
		ActionCard acPunch = new ActionCard(ActionKind.PUNCH);
		ActionCard acRob1 = new ActionCard(ActionKind.ROB);
		ActionCard acRob2 = new ActionCard(ActionKind.ROB);
		ActionCard acShoot1 = new ActionCard(ActionKind.SHOOT);
		ActionCard acShoot2 = new ActionCard(ActionKind.SHOOT);

		this.deck.add(acMove1);
		this.deck.add(acMove2);
		this.deck.add(acChangeFloor1);
		this.deck.add(acChangeFloor2);
		this.deck.add(acMarshal);
		this.deck.add(acPunch);
		this.deck.add(acRob1);
		this.deck.add(acRob2);
		this.deck.add(acShoot1);
		this.deck.add(acShoot2);

		for (ActionCard c : this.deck) {
			c.setBelongsTo(this);
		}

	}

	void createBulletCards() {

		BulletCard bc1 = new BulletCard();
		BulletCard bc2 = new BulletCard();
		BulletCard bc3 = new BulletCard();
		BulletCard bc4 = new BulletCard();
		BulletCard bc5 = new BulletCard();
		BulletCard bc6 = new BulletCard();

		this.bullets.add(bc1);
		this.bullets.add(bc2);
		this.bullets.add(bc3);
		this.bullets.add(bc4);
		this.bullets.add(bc5);
		this.bullets.add(bc6);

		for (BulletCard bc : this.bullets) {
			bc.setBelongsTo(this);
		}

	}

	void createStartingPurse() {
		Money startingPurse = new Money(MoneyType.PURSE, 250);
		this.loot.add(startingPurse);
	}

	void Rob() {
		
		if (!this.position.lootInCabin.isEmpty()) {
			// ask the player of the bandit to choose (get the index)
			int index = 0;
			this.loot.add(this.position.lootInCabin.get(index));
			
		}
	}

}
