package main;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

/**
 * CarType enumeration definition. Generated by the TouchCORE code generator.
 */
public enum CarType implements SerializableSFSType {
	LocomotiveRoof, LocomotiveCabin, StagecoachRoof, StagecoachCabin, Car1Roof, Car1Cabin, Car2Roof, Car2Cabin,
	Car3Roof, Car3Cabin, Car4Roof, Car4Cabin, Car5Roof, Car5Cabin, Car6Roof, Car6Cabin
}
