package main;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

/**
 * GameStatus enumeration definition.
 * Generated by the TouchCORE code generator.
 */
public enum GameStatus implements SerializableSFSType {
    SETUP, SCHEMIN, STEALIN, COMLETED
}
