package main;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

/**
 * HostageType enumeration definition.
 * Generated by the TouchCORE code generator.
 */
public enum HostageType implements SerializableSFSType {

}
