package main;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

// Start of user code for imports
// End of user code

/**
 * Hostage class definition.
 * Generated by the TouchCORE code generator.
 */
public class Hostage implements SerializableSFSType {
    
    protected HostageType hostageType;
    protected Bandit capturedBy;
    
    public Hostage() { }
    
    Bandit getCapturedBy() {
        return this.capturedBy;
    }

    boolean setCapturedBy(Bandit newObject) {
        this.capturedBy = newObject;
        return true;
    }
}
