package main;

import java.util.ArrayList;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

// Start of user code for imports
// End of user code

/**
 * Loot class definition.
 * Generated by the TouchCORE code generator.
 */
public abstract class Loot implements SerializableSFSType {
    
    protected boolean isWhiskey;
    
    // NEEDED FOR SERIALIZATION
    public Loot() { }
}
