package main;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

// Start of user code for imports
// End of user code

/**
 * Marshal class definition.
 * Generated by the TouchCORE code generator.
 */
public class Marshal implements SerializableSFSType {
    
    protected TrainUnit marshalPosition;
    protected static Marshal instance;

    public Marshal() {}
    
    public TrainUnit getMarshalPosition() {
        return this.marshalPosition;
    }

    public void setMarshalPosition(TrainUnit newObject) {
        this.marshalPosition = newObject;
    }

    public static getInstance(){
        if (instance==null){
            instance = new Marshal();
        }
        return instance;
    }
}
