package main;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

/**
 * MoneyType enumeration definition.
 * Generated by the TouchCORE code generator.
 */
public enum MoneyType implements SerializableSFSType {
    PURSE, STRONGBOX, RUBY
}
