package main;

import com.smartfoxserver.v2.protocol.serialization.SerializableSFSType;

// Start of user code for imports
// End of user code

/**
 * Whiskey class definition.
 * Generated by the TouchCORE code generator.
 */
public class Whiskey extends Loot implements SerializableSFSType {
    
    protected WhiskeyType whiskeyType;
    protected WhiskeyStatus whiskeyStatus;
    
    public Whiskey() { }
}
